### ISSUE TITLE
Doubts about the limitation in the appendix of the paper

### ISSUE THREAD

**Issue by lmc8133** [LukeForeverYoung/QRNet#5]
Thank you for your excellent work!
I have some questions about the paper. What do you mean "Due to the lack of fine-grained multimodal interaction, we still need a post-interaction module in the visual grounding framework". Which part of your model is the post-interaction module?
And what can fine-grained multimodal interaction be?

**Comment by LukeForeverYoung** [comment]
We follow the TransVG framework. The VL-Transformer behind the visual and language backbones is the module we called "post-interaction." We consider that taking the CLS token to represent the whole sentence to interact with the visual feature is coarse-grained. If we could take the token-level feature, the interaction would be fine-grained.
